name: masoukharid
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  adobe_xd: ^2.0.1
  flutter_svg: ^1.0.3
  page_transition: ^2.0.5
  lottie: ^1.2.2
  flutter_image_slideshow: ^0.1.2
  flutter_speed_dial: ^6.0.0
  http: ^0.13.4
  font_awesome_flutter: ^10.1.0
  otp_text_field: ^1.1.2
  animate_icons: ^2.0.0
  percent_indicator: ^4.0.0
  image_picker: ^0.8.4+11
  dio: ^4.0.4
  shared_preferences: ^2.0.13
  internet_connection_checker: ^0.0.1+3
  check_vpn_connection: ^0.0.2
  flutter_secure_storage: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:


  uses-material-design: true

  assets:
    - assets/lottieJSON/
    - images/
    - images/Icons/
    - images/SettingsIcons/
    - images/BottomNavigationBarIcons/
    - images/HeaderPics/

  fonts:
    - family: Snaap
      fonts:
        - asset: fonts/SNAAP.ttf
    - family: Dana
      fonts:
        - asset: fonts/DANA-BOLD.ttf
        - asset: fonts/DANA-REGULAR.ttf
    - family: IranYekan
      fonts:
        - asset: fonts/IRANYEKANWEBBLACKFANUM.ttf
        - asset: fonts/IRANYEKANWEBBOLDFANUM.ttf
        - asset: fonts/IRANYEKANWEBEXTRABLACKFANUM.ttf
        - asset: fonts/IRANYEKANWEBLIGHTFANUM.ttf
        - asset: fonts/IRANYEKANWEBMEDIUMFANUM.ttf
        - asset: fonts/IRANYEKANWEBREGULARFANUM.ttf
        - asset: fonts/IRANYEKANWEBTHINFANUM.ttf
    - family: IranYekanExtraBold
      fonts:
        - asset: fonts/IRANYEKANWEBEXTRABOLDFANUM.ttf

    - family: IranSans
      fonts:
        - asset: fonts/IRANSANS.ttf
